name: resonance-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - pip
  - pytest
  - pytest-cov
  - coverage
  - sphinx
  - numpy
  - scipy
  - matplotlib >=2.1
  - pandas
  - sympy
  - notebook<5.1  # notedown can't work with newer
  - ipywidgets
  - nbconvert
  - jupyter_contrib_nbextensions
  - pip:
    - https://github.com/moorepants/rst-to-ipynb/archive/pycon-funcs.zip
