name: resonance
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - pip
  - numpy
  - scipy
  - matplotlib >=2.1
  - pandas
  - sympy
  - notebook
  - ipywidgets
  - jupyter_contrib_nbextensions
  - pip:
    - resonance
